name: Pull request / Terraform
on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**.md'

env:
  AWS_REGION: eu-west-2


jobs:
  build:
    environment: aws-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform init
        run: |
          terraform init

      - name: Generate plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true




      

