name: Terraform Main - Plan
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

env:
  AWS_REGION: eu-west-2
  TF_ACTIONS_WORKING_DIR: terraform


jobs:
  build:
    environment: aws-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


      - name: Check formatting
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: |
          terraform init

      - name: Validate configuration
        id: validate
        run: terraform validate -no-color

      - name: Generate plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Apply plan Terraform
        id: apply
        run: terraform apply -auto-approve

      




      

